<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Reservation;

/**
* ChambreRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class ChambreRepository extends \Doctrine\ORM\EntityRepository
{
    public function liste()
    {
    $qb = $this->_em->createQueryBuilder()
    ->select('l')
    ->from($this->_entityName, 'l');

    return $qb
    ->getQuery()
    ->getResult();
    }

    public function listeOpti()
    {
    $qb = $this->_em->createQueryBuilder()
    ->select('l')
    ->from($this->_entityName, 'l');

    return $qb
    ->getQuery()
    ->getArrayResult();
    }

    public function listeDisponiblesByHotel($hotel, $dateDep, $dateArr)
    {
        /*$qb = $this->_em->createQueryBuilder()
            ->select('c')
            ->from($this->_entityName, 'c')
            ->innerJoin('c.reservation', 'r' )
            ->innerJoin('c.Hotel' , 'r
            ->where('c.Hotel = :idHotel')
            ->setParameter('idHotel', $hotel)
            ->setParameter('reservation', $this->_em->getRepository('AppBundle:Reservation')->findAll(), Reservation::class)
            ->andWhere('c.disponible = true');*/

        $qb = $this->_em->createQueryBuilder()
            ->select('c')
            ->from($this->_entityName, 'c');

        /*SELECT * FROM chambre c
        INNER JOIN reservation r ON c.id = r.chambre_id
        WHERE hotel = $hotel
        AND (dateArr > $dateDebutVac AND dateDep > $dateDebutVac)
        OR (dateArr < $dateDebutVac AND dateDep < $dateDebutVac)
        OR (dateArr > $dateFinVac AND dateDep < $dateDebutVac)*/

        return $qb->getQuery()
            ->getResult();
    }
}